language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

after_success:
    - gradle jacocoTestReport
    - bash <(curl -s https://codecov.io/bash) -t 06a3e6e8-ddf4-4950-b2e0-2a3483c3716c