language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

test:
    post:
        - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
        - bash <(curl -s https://codecov.io/bash) -t 06a3e6e8-ddf4-4950-b2e0-2a3483c3716c